### ISSUE TITLE
Undefined index: glyf - phenx/php-font-lib/src/FontLib/TrueType/File.php, line 329

### ISSUE THREAD

**Issue by consolibyte** [dompdf/php-font-lib#65]
PHP 7.0.6

The line in question is this: 

```
  /**
   * @param $name
   *
   * @return Table
   */
  public function getTableObject($name) {
    return $this->data[$name];
  }
```

**Comment by bsweeney** [comment]
Dompdf doesn't support OTF fonts at present. Do you have TTF versions?

**Comment by keith-chargeover** [comment]
That's interesting... since the OTF versions were working fine up until I upgraded to DomPDF 8.0.1. 

I do have the TTF versions, but they result in the same error message. However, the TTF versions I have were converted from the OTF versions.

**Comment by bsweeney** [comment]
I'd be curious to see a sample HTML document and the resulting render from before. But you might open an issue in the Dompdf project since that's a concern not directly related to this error. With Dompdf 0.8.0 we added more checks in the font management portion of Dompdf to prevent processing of non-TTF files. Still, in earlier version I wouldn't expect Dompdf to process the font correctly.

**Comment by onassar** [comment]
I'm also getting this with specific fonts.

**Comment by bsweeney** [comment]
Not that this error occurs when attempting to subset a font that does not include a glyf table. A number of OpenType fonts use the CFF table instead. For full support ensure any font you're attempting to parse includes a glyf table.

Watch #10 for updates.
